


#Esta línea indica que lo siguiente será una definición de "servicios". 
#En Docker Compose, un servicio representa un contenedor que ejecuta una aplicació
services: 
#Define un servicio llamado server. Este es el nombre que se le da al contenedor que será creado. Puede ser cualquier nombre que desees.
  server:
  #ndica que el servicio server será creado a partir de una imagen Docker que se construye localmente 
  #(no a partir de una imagen preexistente en un repositorio).
    build:
    #Define el "contexto" de construcción para Docker. El contexto es el directorio desde el cual se ejecutará el comando docker build. 
    #En este caso, el . indica que el contexto es el directorio actual donde se encuentra el archivo docker-compose.yml.
      context: .
      #Establece un mapeo de puertos entre el contenedor y la máquina host. 
      #Este mapeo permite que las aplicaciones dentro del contenedor sean accesibles desde fuera del contenedor a través de puertos específicos.
    ports:
    #Mapea el puerto 8000 del contenedor al puerto 8000 del host.
    #Esto significa que cualquier tráfico que llegue al puerto 8000 en la máquina host será dirigido al puerto 8000 dentro del contenedor.
      - 8000:8000

